import { describe, expect, it } from 'vitest';

import { GcodeParseError, parseGcodeFacts } from '../../src/gcode/index.js';

const limits = {
  maximumInputBytes: 10_000,
  maximumLines: 100,
  maximumLineBytes: 1_000,
  maximumSegments: 20,
  maximumMetadataEntries: 20,
};

const encode = (value: string): Uint8Array => new TextEncoder().encode(value);

describe('bounded G-code compatibility fact parsing', () => {
  it('extracts common Prusa/Orca metadata with evidence and movement bounds', () => {
    const facts = parseGcodeFacts(
      encode(`; generated by PrusaSlicer 2.9.0
; printer_model = MK4S
; gcode_flavor = marlin2
; nozzle_diameter = 0.4, 0.4
; extruder_count = 2
G90
G1 X10 Y20 Z0.2 E1
G1 X110 Y70 Z20 E2
`),
      limits,
    );

    expect(facts).toMatchObject({
      schemaVersion: 1,
      parser: { name: 'yuki-gcode', version: '1.0.0' },
      targetPrinter: { status: 'known', value: 'mk4s' },
      flavor: { status: 'known', value: 'marlin2' },
      nozzleDiametersMm: { status: 'known', value: [0.4, 0.4] },
      extruderCount: { status: 'known', value: 2 },
      buildBounds: {
        status: 'known',
        value: {
          minimum: { x: 10, y: 20, z: 0.2 },
          maximum: { x: 110, y: 70, z: 20 },
          size: { width: 100, depth: 50, height: 19.8 },
          unit: 'mm',
        },
      },
      statistics: { linesRead: 8, movementSegments: 2 },
    });
    expect(facts.targetPrinter.status === 'known' && facts.targetPrinter.evidence[0]).toEqual({
      source: 'comment',
      line: 2,
      key: 'printer_model',
    });
  });

  it('recognizes Cura metadata and tool selections', () => {
    const facts = parseGcodeFacts(
      encode(`;Generated with Cura_SteamEngine 5.8
;FLAVOR:Marlin
;TARGET_MACHINE.NAME:Ender-3 V3
;NOZZLE_DIAMETER:0.6
T1
G1 X0 Y0 Z0.2
`),
      limits,
    );
    expect(facts.slicer).toMatchObject({ status: 'known', value: 'cura_steamengine 5.8' });
    expect(facts.flavor).toMatchObject({ status: 'known', value: 'marlin' });
    expect(facts.targetPrinter).toMatchObject({ status: 'known', value: 'ender-3 v3' });
    expect(facts.nozzleDiametersMm).toMatchObject({ status: 'known', value: [0.6] });
    expect(facts.extruderCount).toMatchObject({ status: 'known', value: 2 });
  });

  it('keeps missing and conflicting facts conservatively unknown', () => {
    const missing = parseGcodeFacts(encode('G1 X10 Y20\n'), limits);
    expect(missing.buildBounds).toEqual({ status: 'unknown', reason: 'incomplete' });
    expect(missing.targetPrinter).toEqual({ status: 'unknown', reason: 'not-found' });

    const conflicting = parseGcodeFacts(
      encode('; printer_model = Alpha\n; printer_model = Beta\n'),
      limits,
    );
    expect(conflicting.targetPrinter).toEqual({ status: 'unknown', reason: 'ambiguous' });
  });

  it.each([
    ['an arc', 'G90\nG1 X0 Y0 Z0.2\nG2 X10 Y10 I5 J0\nG1 X20 Y20 Z1'],
    ['a coordinate reset', 'G90\nG1 X0 Y0 Z0.2\nG92 X0\nG1 X20 Y20 Z1'],
    ['relative motion before an origin', 'G91\nG1 X10 Y10 Z0.2\nG90\nG1 X20 Y20 Z1'],
    ['homing', 'G90\nG1 X0 Y0 Z0.2\nG28 X Y\nG1 X20 Y20 Z1'],
    ['inch units', 'G20\nG1 X0 Y0 Z0.2\nG1 X20 Y20 Z1'],
    ['an unsupported compact move', 'G90\nG1 X0 Y0 Z0.2\nG1X200Y200Z1\nG1 X20 Y20 Z1'],
  ])('does not understate build bounds when input contains %s', (_name, source) => {
    expect(parseGcodeFacts(encode(source), limits).buildBounds).toEqual({
      status: 'unknown',
      reason: 'incomplete',
    });
  });

  it.each([
    ['bytes', encode('G1 X1'), { ...limits, maximumInputBytes: 4 }, 'input-too-large'],
    ['lines', encode('a\nb\nc'), { ...limits, maximumLines: 2 }, 'line-limit-exceeded'],
    ['line bytes', encode('12345'), { ...limits, maximumLineBytes: 4 }, 'line-too-long'],
    [
      'segments',
      encode('G1 X1 Y1 Z1\nG1 X2 Y2 Z2'),
      { ...limits, maximumSegments: 1 },
      'segment-limit-exceeded',
    ],
    [
      'metadata entries',
      encode('; FLAVOR:Marlin\n; FLAVOR:Marlin'),
      { ...limits, maximumMetadataEntries: 1 },
      'metadata-limit-exceeded',
    ],
  ])('enforces the configured %s limit', (_name, input, bounded, code) => {
    expect(() => parseGcodeFacts(input, bounded)).toThrowError(
      expect.objectContaining({ name: 'GcodeParseError', code }),
    );
  });

  it('rejects hostile numeric and text input without reflecting it in errors', () => {
    for (const input of [encode('G1 XNaN Y0 Z0'), encode('G1 X1e999 Y0 Z0')]) {
      try {
        parseGcodeFacts(input, limits);
        throw new Error('expected parsing to fail');
      } catch (error) {
        expect(error).toBeInstanceOf(GcodeParseError);
        expect(error).toMatchObject({ code: 'invalid-number' });
        expect((error as Error).message).not.toContain('NaN');
        expect((error as Error).message).not.toContain('1e999');
      }
    }
    expect(() => parseGcodeFacts(new Uint8Array([0xff]), limits)).toThrowError(
      expect.objectContaining({ code: 'invalid-input' }),
    );
  });

  it('rejects invalid limits before parsing', () => {
    expect(() => parseGcodeFacts(new Uint8Array(), { ...limits, maximumLines: 0 })).toThrow(
      RangeError,
    );
  });
});
